apiVersion: v1
kind: Service
metadata:
  name: helloservice
spec:
  selector:
    app: helloservice
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3030
    targetPort: 3030
    nodePort: 31110