apiVersion: v1
kind: Service
metadata:
  name: worldservice
spec:
  selector:
    app: worldservice
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 31120